GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001//api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
   "name": "post after connecting to database",
   "number": "040-123456"
}