GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/64f45705bbba8f8578f4cee3

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
   
    "author":456,
    "url":"http://url.com"
    
}