GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/64f45705bbba8f8578f4cee7

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title":"blog",
    "author":"test",
    "url":"http://url.com"
    
}